[tableau]
token_name="MyToken"
personal_access_token = "ZpGk5qMJQIytxtHerljfTg==:22aDQjNYtWww9McC5pabyXY1qqGwkcs7"
server_url = "https://prod-useast-a.online.tableau.com/"
site_id = "Site21"



[passwords]
alice_foo = "streamlit123"
bob_bar = "mycrazypw"
